CREATE TABLE Event (
	ProductSN VARCHAR(20),
    Author VARCHAR(50),
    Description VARCHAR(200),
    CreationTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    Type VARCHAR(20),
    CONSTRAINT pk_Event PRIMARY KEY (ProductSN, CreationTime),
	CONSTRAINT fk_ESN FOREIGN KEY (ProductSN) REFERENCES Product(ProductSN)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
    CONSTRAINT fk_EventType FOREIGN KEY (Type) REFERENCES EventType(Type)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);