CREATE TABLE Bin (
    BinID VARCHAR(20),
    ShelfID VARCHAR(20),
    AligniLocationID INTEGER,
    CONSTRAINT pk_BinID PRIMARY KEY (BinID),
    CONSTRAINT fk_ShelfID FOREIGN KEY (ShelfID) REFERENCES Shelf(ShelfID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
);