CREATE TABLE StoredPCBGroup (
    PCBGroupSN VARCHAR(20),
    StorageBoxSN VARCHAR(20),
    CONSTRAINT pk_StoredPCBGroup PRIMARY KEY (PCBGroupSN),
    CONSTRAINT fk_StoredPCBGroupSN FOREIGN KEY (PCBGroupSN) REFERENCES PCBGroup(PCBGroupSN)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT fk_StorageBoxSN FOREIGN KEY (StorageBoxSN) REFERENCES StorageBox(StorageBoxSN)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
);