CREATE TABLE Note (
	ProductSN VARCHAR(20),
	CreationTime DATETIME DEFAULT CURRENT_TIMESTAMP,
	Note VARCHAR(200),
	CONSTRAINT pk_Notes PRIMARY KEY (ProductSN, CreationTime),
	CONSTRAINT fk_SN FOREIGN KEY (ProductSN) REFERENCES Product(ProductSN)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);