CREATE TABLE Shelf (
    ShelfID VARCHAR(20),
    RackID VARCHAR(20),
    CONSTRAINT pk_ShelfID PRIMARY KEY (ShelfID),
    CONSTRAINT fk_RackID FOREIGN KEY (RackID) REFERENCES Shelf(RackID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
);